version: '3.9'
services:
  server:
    build:
      context: ./
      dockerfile: ./Server/DockerfileServer
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ./dev-certs:/root/.aspnet/https/
      - CompanyApiData:/app/data
  client:
    build:
      context: ./
      dockerfile: ./Client/DockerfileClient
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ./dev-certs:/app/keys
volumes:
  CompanyApiData: